# Generated by Django 6.0.8 on 2026-09-16 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criptomoeda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('simbolo', models.CharField(max_length=20, unique=True)),
                ('quantidade', models.DecimalField(decimal_places=10, max_digits=20)),
                ('cotacao_brl', models.DecimalField(decimal_places=8, default=0, help_text='Cotação em BRL (R$ por unidade).', max_digits=20)),
                ('cotacao_usd', models.DecimalField(decimal_places=8, default=0, help_text='Cotação em USD por unidade.', max_digits=20)),
                ('cotacao_btc', models.DecimalField(blank=True, decimal_places=15, help_text='Cotação em BTC por unidade. Só se aplica quando não houver par direto negociado contra BTC (não preencher para o próprio BTC).', max_digits=30, null=True)),
                ('fonte_cotacao', models.CharField(choices=[('manual', 'Manual'), ('api', 'API')], default='manual', max_length=10)),
                ('atualizado_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Criptomoeda',
                'verbose_name_plural': 'Criptomoedas',
                'ordering': ['simbolo'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoCripto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_brl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cotacao_brl', models.DecimalField(decimal_places=8, max_digits=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('moeda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='cripto.criptomoeda')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico da Criptomoeda',
                'verbose_name_plural': 'Históricos das Criptomoedas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
