# Generated by Django 6.0.8 on 2026-09-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cripto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criptomoeda',
            name='auto_cotacao',
            field=models.BooleanField(default=False, help_text='Se marcado, a cotação será atualizada automaticamente pela API selecionada.', verbose_name='Precificação automática via API'),
        ),
        migrations.AddField(
            model_name='criptomoeda',
            name='fonte_api',
            field=models.CharField(choices=[('coingecko', 'CoinGecko'), ('binance', 'Binance'), ('cryptocompare', 'CryptoCompare')], default='coingecko', max_length=15, verbose_name='Fonte da API'),
        ),
        migrations.AddField(
            model_name='criptomoeda',
            name='id_api',
            field=models.CharField(blank=True, default='', help_text='ID usado pela fonte. Ex.: CoinGecko "bitcoin"/"turbo"; Binance/CryptoCompare símbolo "BTC". Em branco, usa o símbolo da moeda.', max_length=64, verbose_name='Identificador na fonte'),
        ),
        migrations.AddField(
            model_name='criptomoeda',
            name='par_cotacao',
            field=models.CharField(choices=[('USD', 'USD/USDT (converter para BRL)'), ('BRL', 'BRL (par direto em real)')], default='USD', help_text='Se a moeda não tiver par direto em real (ex.: TURBOBRL), use USD/USDT — o sistema converte automaticamente para BRL pela taxa de câmbio.', max_length=3, verbose_name='Par de cotação'),
        ),
    ]
