# Generated by Django 6.0.8 on 2026-09-16 14:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('fii', 'FII'), ('acao', 'Ação'), ('etf', 'ETF'), ('outro', 'Outro')], max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=6, max_digits=15)),
                ('preco_medio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('preco_atual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dividend_yield_mensal', models.DecimalField(decimal_places=3, default=0, help_text='Rendimento de proventos mensal estimado (% do valor de mercado/mês).', max_digits=6)),
                ('fonte_preco', models.CharField(choices=[('manual', 'Manual'), ('api', 'API')], default='manual', max_length=10)),
                ('atualizado_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ativo (renda variável)',
                'verbose_name_plural': 'Ativos (renda variável)',
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_mercado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='renda_variavel.ativo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico do Ativo',
                'verbose_name_plural': 'Históricos dos Ativos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProventoRecebido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('tipo', models.CharField(blank=True, default='', help_text='ex.: dividendo, JCP', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proventos', to='renda_variavel.ativo')),
            ],
            options={
                'verbose_name': 'Provento Recebido',
                'verbose_name_plural': 'Proventos Recebidos',
                'ordering': ['-data'],
            },
        ),
    ]
