# Generated by Django 6.0.8 on 2026-09-17 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, default='')),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_inicial', models.DecimalField(decimal_places=2, default=0, help_text='Valor já destinado para este objetivo (fictício, sem movimentação bancária).', max_digits=15)),
                ('taxa_rendimento_pct', models.DecimalField(decimal_places=3, default=0, help_text='Taxa de rendimento mensal (%) considerada nos cotaes.', max_digits=6)),
                ('data_inicio', models.DateField()),
                ('data_conclusao', models.DateField()),
                ('status', models.CharField(choices=[('planejamento', 'Em planejamento'), ('ativo', 'Ativo (refletido no fluxo)'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='planejamento', max_length=15)),
                ('refletir_fluxo', models.BooleanField(default=False, help_text='Se ativo, os aportes planejados aparecem no fluxo de caixa como saídas.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Objetivo Financeiro',
                'verbose_name_plural': 'Objetivos Financeiros',
                'ordering': ['data_conclusao'],
            },
        ),
        migrations.CreateModel(
            name='AporteMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('manual', models.BooleanField(default=False, help_text='Aporte editado manualmente — não é recalculado automaticamente.')),
                ('realizado', models.BooleanField(default=False)),
                ('valor_realizado', models.DecimalField(blank=True, decimal_places=2, help_text='Valor efetivamente aportado (sobrepõe valor planejado no cálculo).', max_digits=15, null=True)),
                ('data_realizado', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes_mensais', to='planejamento.objetivofinanceiro')),
            ],
            options={
                'verbose_name': 'Aporte Mensal',
                'verbose_name_plural': 'Aportes Mensais',
                'ordering': ['ano', 'mes'],
                'unique_together': {('objetivo', 'ano', 'mes')},
            },
        ),
    ]
