# Generated by Django 6.0.8 on 2026-09-16 14:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacaoCDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=200)),
                ('valor_aplicado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_aplicacao', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('percentual_cdi', models.DecimalField(decimal_places=3, default=Decimal('100.000'), help_text='Percentual do CDI contratado (ex.: 100 = 100% do CDI, 110 = 110%).', max_digits=8)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aplicação de CDB',
                'verbose_name_plural': 'Aplicações de CDB',
                'ordering': ['data_aplicacao'],
            },
        ),
        migrations.CreateModel(
            name='TaxaCDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_anual', models.DecimalField(decimal_places=3, max_digits=6)),
                ('data_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Taxa CDI',
                'verbose_name_plural': 'Taxas CDI',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoCDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dias_uteis', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='renda_fixa.aplicacaocdb')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico do CDB',
                'verbose_name_plural': 'Históricos dos CDBs',
                'ordering': ['-criado_em'],
            },
        ),
    ]
