# Generated by Django 6.0.8 on 2026-09-16 14:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Divida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('credor', models.CharField(blank=True, default='', max_length=200)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('data_vencimento', models.DateField(default=django.utils.timezone.localdate)),
                ('num_parcelas', models.PositiveSmallIntegerField(default=1)),
                ('valor_parcela', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('parcelas_restantes', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('em_dia', 'Em dia'), ('a_pagar', 'A pagar (futura)'), ('atrasada', 'Atrasada')], default='a_pagar', max_length=10)),
                ('ativa', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dívida',
                'verbose_name_plural': 'Dívidas',
                'ordering': ['data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoDivida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_restante', models.DecimalField(decimal_places=2, max_digits=15)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('divida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='dividas.divida')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico da Dívida',
                'verbose_name_plural': 'Históricos das Dívidas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
