# Generated by Django 6.0.8 on 2026-09-16 17:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='divida',
            name='para_pagamento',
            field=models.BooleanField(default=False, help_text='Se marcado, as parcelas desta dívida aparecem no fluxo de caixa como pagamento.', verbose_name='Considerar para pagamento'),
        ),
        migrations.AlterField(
            model_name='divida',
            name='data_vencimento',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Data da primeira/renda parcela a pagar.'),
        ),
        migrations.AlterField(
            model_name='divida',
            name='valor_parcela',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deixe em branco para calcular automaticamente (valor_total ÷ nº parcelas).', max_digits=15, null=True),
        ),
        migrations.CreateModel(
            name='ParcelaDivida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('a_pagar', 'A pagar'), ('paga', 'Paga')], default='a_pagar', max_length=10)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('divida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='dividas.divida')),
            ],
            options={
                'verbose_name': 'Parcela da Dívida',
                'verbose_name_plural': 'Parcelas das Dívidas',
                'ordering': ['data_vencimento'],
            },
        ),
    ]
