# Generated by Django 6.0.8 on 2026-09-16 14:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('banco_emissor', models.CharField(blank=True, default='', max_length=200)),
                ('limite_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dia_fechamento', models.PositiveSmallIntegerField(default=1, help_text='Dia do mês em que a fatura fecha (1-28).')),
                ('dia_vencimento', models.PositiveSmallIntegerField(default=10, help_text='Dia do mês em que a fatura vence (1-28).')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cartão de Crédito',
                'verbose_name_plural': 'Cartões de Crédito',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CompraCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('estabelecimento', models.CharField(blank=True, default='', max_length=255)),
                ('categoria', models.CharField(blank=True, default='', max_length=100)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_compra', models.DateField(default=django.utils.timezone.localdate)),
                ('forma_pagamento', models.CharField(choices=[('avista', 'À vista'), ('parcelada', 'Parcelada')], default='avista', max_length=10)),
                ('num_parcelas', models.PositiveSmallIntegerField(default=1)),
                ('valor_parcela', models.DecimalField(blank=True, decimal_places=2, help_text='Deixe em branco para calcular automaticamente (valor_total ÷ nº parcelas).', max_digits=15, null=True)),
                ('cancelada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='cartoes.cartaocredito')),
            ],
            options={
                'verbose_name': 'Compra no Cartão',
                'verbose_name_plural': 'Compras no Cartão',
                'ordering': ['-data_compra'],
            },
        ),
        migrations.CreateModel(
            name='FaturaCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('estado', models.CharField(choices=[('aberta', 'Em aberto'), ('paga', 'Paga'), ('atrasada', 'Atrasada')], default='aberta', max_length=10)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='cartoes.cartaocredito')),
            ],
            options={
                'verbose_name': 'Fatura do Cartão',
                'verbose_name_plural': 'Faturas dos Cartões',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('cartao', 'ano', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='HistoricoCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_disponivel', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_devedor', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='cartoes.cartaocredito')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico do Cartão',
                'verbose_name_plural': 'Históricos dos Cartões',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveSmallIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ano', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('a_vencer', 'A vencer'), ('fatura_atual', 'Na fatura atual'), ('paga', 'Paga')], default='a_vencer', max_length=15)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='cartoes.compracartao')),
                ('fatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelas', to='cartoes.faturacartao')),
            ],
            options={
                'verbose_name': 'Parcela da Compra',
                'verbose_name_plural': 'Parcelas das Compras',
                'ordering': ['ano', 'mes', 'numero_parcela'],
            },
        ),
    ]
