# Generated by Django 6.0.8 on 2026-09-16 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartoes', '0001_initial'),
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaPeriodica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor_esperado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dia_do_mes', models.PositiveSmallIntegerField(default=1)),
                ('recorrência', models.CharField(choices=[('mensal', 'Mensal'), ('quinzenal', 'Quinzenal'), ('semanal', 'Semanal'), ('anual', 'Anual')], default='mensal', max_length=15)),
                ('categoria', models.CharField(blank=True, default='', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cartao_pagamento_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_periodicas', to='cartoes.cartaocredito')),
                ('conta_pagamento_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_periodicas', to='contas.banco')),
            ],
            options={
                'verbose_name': 'Conta Periódica (a pagar)',
                'verbose_name_plural': 'Contas Periódicas (a pagar)',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaContaPeriodica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('a_pagar', 'A pagar (futura)'), ('vencendo_hoje', 'Vencendo hoje'), ('atrasada', 'Atrasada'), ('paga', 'Paga')], default='a_pagar', max_length=15)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta_periodica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='contas_periodicas.contaperiodica')),
                ('movimentacao', models.ForeignKey(blank=True, help_text='Movimentação de saída na conta bancária vinculada à baixa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_conta_periodica', to='contas.movimentacao')),
            ],
            options={
                'verbose_name': 'Ocorrência de Conta Periódica',
                'verbose_name_plural': 'Ocorrências de Contas Periódicas',
                'ordering': ['data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='RecebimentoAvulso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_prevista', models.DateField()),
                ('status', models.CharField(choices=[('a_receber', 'A receber (futuro)'), ('atrasado', 'Atrasado'), ('recebido', 'Recebido')], default='a_receber', max_length=10)),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('valor_recebido', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recebimentos_avulsos', to='contas.banco')),
                ('movimentacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_recebimento_avulso', to='contas.movimentacao')),
            ],
            options={
                'verbose_name': 'Recebimento Avulso',
                'verbose_name_plural': 'Recebimentos Avulsos',
                'ordering': ['data_prevista'],
            },
        ),
        migrations.CreateModel(
            name='RecebimentoPeriodico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor_esperado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dia_do_mes', models.PositiveSmallIntegerField(default=1)),
                ('recorrência', models.CharField(choices=[('mensal', 'Mensal'), ('quinzenal', 'Quinzenal'), ('semanal', 'Semanal'), ('anual', 'Anual')], default='mensal', max_length=15)),
                ('categoria', models.CharField(blank=True, default='', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta_destino_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recebimentos_periodicos', to='contas.banco')),
            ],
            options={
                'verbose_name': 'Recebimento Periódico',
                'verbose_name_plural': 'Recebimentos Periódicos',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaRecebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prevista', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('a_receber', 'A receber (futuro)'), ('atrasado', 'Atrasado'), ('recebido', 'Recebido')], default='a_receber', max_length=10)),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('valor_recebido', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('movimentacao', models.ForeignKey(blank=True, help_text='Movimentação de entrada na conta bancária vinculada à baixa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_recebimento', to='contas.movimentacao')),
                ('recebimento_periodico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='contas_periodicas.recebimentoperiodico')),
            ],
            options={
                'verbose_name': 'Ocorrência de Recebimento',
                'verbose_name_plural': 'Ocorrências de Recebimentos',
                'ordering': ['data_prevista'],
            },
        ),
    ]
