# Generated by Django 6.0.8 on 2026-09-16 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
        ('contas_periodicas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoAvulso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_pagamento', models.DateField(verbose_name='Data de pagamento')),
                ('status', models.CharField(choices=[('a_pagar', 'A pagar (futuro)'), ('vencendo_hoje', 'Vencendo hoje'), ('atrasado', 'Atrasado'), ('pago', 'Pago')], default='a_pagar', max_length=15)),
                ('data_efetiva_pagamento', models.DateField(blank=True, null=True, verbose_name='Data efetiva do pagamento')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_avulsos', to='contas.banco')),
                ('movimentacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_pagamento_avulso', to='contas.movimentacao')),
            ],
            options={
                'verbose_name': 'Pagamento Avulso',
                'verbose_name_plural': 'Pagamentos Avulsos',
                'ordering': ['data_pagamento'],
            },
        ),
    ]
