# Generated by Django 6.0.8 on 2026-09-16 14:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaPoupanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('instituicao', models.CharField(blank=True, default='', max_length=200)),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('usar_regra_selic', models.BooleanField(default=True, help_text='Aplica a regra oficial da poupança (0,5% + TR quando Selic > 8,5% a.a., ou 70% da Selic + TR quando ≤ 8,5% a.a.).')),
                ('taxa_fixa_mensal', models.DecimalField(decimal_places=3, default=Decimal('0.50'), help_text='Taxa mensal (%) usada quando "usar_regra_selic" está desativado.', max_digits=6)),
                ('taxa_selic_anual', models.DecimalField(decimal_places=3, default=Decimal('10.500'), help_text='Taxa Selic vigente (% a.a.), usada para aplicar a regra da poupança.', max_digits=6)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conta Poupança',
                'verbose_name_plural': 'Contas Poupança',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPoupanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='poupanca.contapoupanca')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico da Poupança',
                'verbose_name_plural': 'Históricos da Poupança',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoPoupanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('aporte', 'Aporte'), ('retirada', 'Retirada')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='poupanca.contapoupanca')),
            ],
            options={
                'verbose_name': 'Movimentação de Poupança',
                'verbose_name_plural': 'Movimentações de Poupança',
                'ordering': ['-data'],
            },
        ),
    ]
